# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Aarathi Devakumar's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Aarathi Devakumar
headline: Sophomore Mechatronics Engineering Student at Texas A&M University
description: >- # dont remove this line. this will ignore all new lines until the next section
  Howdy! I'm Aarathi, a sophomore engineering student at Texas A&M University pursing a bachelor's in Mechatronics, Automation, and Robotics Engineering!
  My interests are in robotics and mechatronics, and I have experience in the subject starting from a young age. Ever since competing in middle school robotics with my Girl Scout Troop, I instantly fell in love with the process of designing a robot. I later researched various types of robots and was amazed by how they could help others live a better life and shape the world, and I strive to be part of that process. I have experience in machining, CAD, design, prototyping, and testing. I aim to discover ways to combine my technical experiences in robotics along with various fields such as defense or manufacturing, but particularly in fashion design, designing clothing that is stunning by aesthetics and automation. 
  As a woman in STEM, I also aim to empower girls to find an interest in STEM by participating and organizing outreach programs. I currently have an engineering instagram that shares my experiences as a female engineering student: girlypopengineer.
  Outside of robotics and design, I have a background in music. I have played piano for 13 years and the violin for 7 years. I continue playing the violin through the Texas A&M Chamber Orchestra and still play the piano for fun.


# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/IMG_0713.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://docs.google.com/document/d/1oEPCM0SKfm8Uo8eC7dF80dcCVEpvr2vlb7MsPrM3YNI/edit?usp=sharing

# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: aarathi-devakumar    # https://www.linkedin.com/in/aarathi-devakumar/ 
  github: aggieart    # https://github.com/aggieart 
  instragram: girlypopengineer      # https://instagram.com/girlypopengineer 
  youtube: aarathidevakumar6249          # https://youtube.com/@aarathidevakumar6249 
  discord: swiftieartichoke           # https://discord.com/users/swiftieartichoke  
  
# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - Robotics
  - Autodesk Inventor, Fusion 360, Onshape
  - SolidWorks
  - 3D Printing
  - CAM
  - Java
  - Python
  - HTML
  - CSS
  - MatLab
  - Soldering
  - Embedded Systems
  - Problem-Solving
  - Team/Project Management
interests:
  - Robotics
  - Mechatronics
  - Automation
  - Embedded Systems Integration
  - Design
  - Sustainability
  - Fashion Design
  - STEM Education
miscellaneous:
  - Music Performance
  - Violin
  - Piano
  - Italian (Elementary Proficiency)
  - Photography
  - Social Media Content Creation
  - Chess (320 Elo Rating)


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{mgvybzbg}


# Active theme (Update this to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

# A few examples. 
  # basic theme:
  #   text: "#1a1c20"
  #   border: "#ddd"
  #   link: "#4a76ee"
  #   highlight: "#0c0cf2"
  #   background: "#ffffff"
  #   light_background: "#f3f5fb"
    
  #   mint theme:
  #   text: "#2c3333"
  #   border: "#e0f2ef"
  #   link: "#40b3a2"
  #   highlight: "#2a9d8f"
  #   background: "#f7fbfa"
  #   light_background: "#f0f9f7"
    
  # lemon theme:
  #   text: "#2d2926"
  #   border: "#f7f3e3"
  #   link: "#ffc94d"
  #   highlight: "#ffb800"
  #   background: "#fffdf5"
  #   light_background: "#fff9e6"
    
  #   pink theme:
  #   text: "#2d2d2d"
  #   border: "#f8e2e2"
  #   link: "#ff8fa3"
  #   highlight: "#ff4d6d"
  #   background: "#fff8f8"
  #   light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
